# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names; during revision
# generate, the timezone variable is available in addition to the
# standard ones.
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to include in patch "slug"
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command,
# regardless of autogenerate being used or not
# revision_environment = false

# set to 'true' to allow .pyc files to be created; otherwise
# the environment will try to avoid creating them
# sourceless = false

# version location specification; this defaults
# to migrations/versions.  When using multiple version
# directories, initial revs will go to version_locations[0],
# and any subsequent revisions will go to the directory
# where the head revision exists.
# version_locations = %(here)s/bar:%(here)s/bat:migrations/versions

# the standard library log formatting control sections are [loggers], [handlers], [formatters]
# and [logger_alembic], [handler_console], [formatter_generic]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine
# "level = INFO" logs SQL queries.
# "level = DEBUG" logs SQL queries and results.
# "level = WARN" logs neither.

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
